service: x-career-search
frameworkVersion: "3"
provider:
  name: aws
  runtime: python3.9
  stage: dev
  timeout: 30
  region: ap-northeast-1

custom:
  app: x-career-search
  pythonRequirements:
    dockerizePip: true
    layer:
      name: ${self:custom.app}
      description: XChange Career - search
      compatibleRuntimes:
        - python3.9

functions:
  app:
    package:
      individually: true
      patterns:
        - "!requirements.txt"
        - "!package.json"
        - "!package-lock.json"
        - "!.serverless/**"
        - "!.vscode/**"
        - "!venv/**"
        - "!**/**.sh"
        - "!node_modules/**"
        - "!integration/**"
        - "!test/**"
        - "!__pycache__/**"
        - "!**/__pycache__/**"
    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}
plugins:
  - serverless-python-requirements
