service: X-Career-Search
app: X-Career-Search
frameworkVersion: "3"
provider:
  name: aws
  runtime: python3.9
  stage: de
  timeout: 30
custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: x-career-user
      description: XChange Career - User
      compatibleRuntimes:
        - python3.9

functions:
  searchApp:
    package:
      individually: true
      patterns:
        - "!requirements.txt"
        - "!package.json"
        - "!package-lock.json"
        - "!.serverless/**"
        - "!.venv/**"
        - "!node_modules/**"
        - "!integration/**"
        - "!test/**"
        - "!__pycache__/**"
        - "!**/__pycache__/**"

    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}
plugins:
  - serverless-python-requirements
